/**
 * SensiSat viewer.
 *
 * The one idea that makes this work without a server: our rasters encode the YEAR
 * a pixel was first built, not whether it was built in a given year. So moving the
 * time slider does not fetch anything — it changes a threshold in a GPU style
 * expression applied to pixels already in memory. One file per island per layer,
 * a few megabytes, read straight off static hosting by HTTP range request.
 *
 * That is also why the frontend is OpenLayers rather than MapLibre: colouring a
 * raster BY PIXEL VALUE is the whole mechanism, and MapLibre still cannot do it
 * (maplibre-gl-js#4479, open, unreleased). Without it every year would need its
 * own pre-rendered tiles — precisely the tile server this design avoids.
 */
// Imported as OLMap, NOT as Map. `import Map from 'ol/Map.js'` shadows the
// JavaScript built-in for the whole module, so a later `new Map()` silently builds
// an OpenLayers map instead of a hash — which fails at the first `.has()` with
// "is not a function", nowhere near the import that caused it. Found exactly that
// way while wiring the readout's file cache.
import OLMap from 'ol/Map.js';
import View from 'ol/View.js';
import TileLayer from 'ol/layer/Tile.js';
import WebGLTileLayer from 'ol/layer/WebGLTile.js';
import XYZ from 'ol/source/XYZ.js';
import TileWMS from 'ol/source/TileWMS.js';
import GeoTIFF from 'ol/source/GeoTIFF.js';
// geotiff.js directly, for COUNTING rather than drawing. It is already here as
// OpenLayers' own dependency, so this costs no bundle weight. OL's GeoTIFF source
// reads whatever resolution the map needs; the readout needs full resolution and a
// window of its own choosing, which is a different question asked of the same file.
import { fromUrl, Pool } from 'geotiff';
import {
  YEAR_OFFSET, UNDATED, FAR_ONLY_KINDS,
  regimeFor, blockSpan, rowAreas, areaHistogram, statsFromHistogram, addedSince,
  islandsInView, sumStats, describe, emptyStats,
} from './count.js';
// Every live figure shown in the UI. Generated by scripts/sync_docs.py from
// sensisat/facts.py; cog cannot be used inside JavaScript (nested array literals end
// in its own "]]]" token), so the key store is a module rather than a marker.
import { FACTS } from './facts.generated.js';


/**
 * Where the published data sits.
 *
 * Three layouts are valid and all must work without a build-time rewrite: the
 * repository (viewer/ beside data/processed/), a local dist/site/ preview, and the
 * deployed site, whose rasters live in an R2 bucket because Cloudflare's asset
 * platform ignores the `Range` header and R2 honours it natively.
 *
 * The ORDER is chosen by hostname rather than simply trying the remote first, and
 * that is the whole point of this block: on a developer's machine a freshly rebuilt
 * layer must win over the published copy. Preferring the remote would quietly show
 * last week's data while the new build sat unused on disk — the silent-staleness
 * failure of CLAUDE.md #20 wearing a different hat. In production neither relative
 * path exists, so putting R2 first there costs nothing and saves two 404s on the
 * critical path before the map can draw.
 */
// The bucket root, for every deployment. There is deliberately no branch-only
// variant of this any more.
//
// It was 'https://data.sensisat.org/v2' while this viewer ran beside production,
// because index.json sits at ONE well-known URL that both viewers fetch and the two
// read different shapes from it — the deployed one wants `islands[island].asset`,
// this one wants `layers[id].asset`. A prefix kept them apart, at the cost of a flag
// day: whichever side moved second would break, silently, with the page still
// answering 200 and the layers simply never drawing. That failure happened once
// already (2026-09-24) and a constant marked branch-only is a poor defence against
// it happening again on merge day.
//
// publish.py now emits BOTH shapes into the one file (see runtime_index), so it
// satisfies either viewer and the two can be deployed in any order, or weeks apart.
const R2_DATA = 'https://data.sensisat.org';
const LOCAL_DATA = ['data', '../data/processed'];
const DATA_CANDIDATES = /^(localhost|127\.0\.0\.1|\[::1\])$/.test(location.hostname)
  ? [...LOCAL_DATA, R2_DATA]
  : [R2_DATA, ...LOCAL_DATA];
let DATA = DATA_CANDIDATES[0];

const C = {
  built:   [255, 178, 0, 1],      // amber — dated built-up
  added:   [255, 90, 60, 1],      // red — appeared since the chosen year
  undated: [150, 110, 220, 1],    // violet — built, year unknown (never a guess)
  green:   [80, 210, 140, 1],
  loss:    [255, 70, 70, 1],
  gain:    [90, 200, 255, 1],
};

/**
 * How each published layer is read and drawn. Mirrors sensisat/layers.py — the
 * encodings are the contract between the build and this file.
 */
const LAYERS = {
  'buildings-dated': {
    title: 'Buildings, dated (cadastre)',
    note: 'Every registered building and the year it was built. One method from 1900 to 2020, so there is no seam anywhere in it.',
    kind: 'year', min: 1900, max: 2026, start: 2020,
  },
  'settlement-era-a': {
    title: 'Settlement extent to 2015',
    // Live figures come from facts.generated.js — one definition shared with the
    // prose page and the STAC descriptions. Never type a number into these strings.
    note: `Settlement clusters including roads, from WSF Evolution. ${FACTS.undated_pct} % of the footprint has no year and is drawn in its own colour.`,
    kind: 'year', min: 1985, max: 2015, start: 2015,
    seam: `Ends at 2015. The 2016+ view is a different instrument, resolution and definition — on the ${FACTS.seam_main_islands} main islands extent drops ${FACTS.seam_drop_lo_pct}–${FACTS.seam_drop_hi_pct} % at the join with nothing demolished.`,
  },
  'settlement-era-b': {
    title: 'Settlement extent 2016 →',
    note: 'WSF Tracker, twice a year, greenhouses removed. Epoch 1 is a baseline: everything standing by July 2016, not what was built that year.',
    kind: 'epoch', min: 2016.5, max: 2026, start: 2026,
    seam: 'Starts at 2016 and is NOT continuous with the layer above. Do not add the two together — they share the 2016 baseline.',
  },
  'covered-agriculture': {
    title: 'Covered agriculture (greenhouses)',
    note: 'Removed from the urban layers and published separately: radar reads plastic as structure, so WSF Tracker calls 72 % of these parcels built-up.',
    kind: 'binary',
  },
  'density-current': {
    title: 'Sealed surface, 2024',
    note: `Percent of each pixel sealed by anything impermeable — buildings, roads, car parks, paving. About ${FACTS.sealed_vs_built}× GHSL’s built surface; the gap is the roads.`,
    kind: 'percent',
  },
  'density-trend': {
    title: 'Built surface trend (GHSL)',
    note: 'Square metres of built surface per ~92 m cell. The only source measuring density consistently across the 2015/2016 seam.',
    kind: 'trend', epochs: [1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020], start: 2020,
  },
  'loss-events': {
    title: 'Built-up gained and lost',
    note: 'The only layer that can show something disappear. Everything else here is growth-only by construction.',
    kind: 'change',
  },
};

const el = (id) => document.getElementById(id);
const status = (msg, bad) => { const s = el('status'); s.textContent = msg; s.classList.toggle('error', !!bad); };

// `scope` is what the readout is currently describing — see updateScope(). It is
// null until the first view has been measured, and cleared whenever the layer
// changes, because a scope belongs to one layer and showing another layer's number
// under this layer's name is the stale-figure failure the gates exist to prevent.
const state = { catalog: null, areaTable: null, scope: null, layer: 'buildings-dated',
                mode: 'state', year: 2020, basemap: 'light', playing: null };

/* ---------------------------------------------------------------- catalogue */
async function json(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.json();
}
const resolve = (base, href) => new URL(href, base).href;

/**
 * Learn what has been published.
 *
 * One request, not sixty-five. Walking the STAC catalogue means fetching the
 * catalogue, then 7 collections, then 56 items — 64 round trips before the first
 * pixel can be drawn. STAC's nested form is right for a catalogue somebody
 * browses with their own tools, and it is still published for exactly that; it is
 * the wrong shape for a page load, so the build also emits a flat index.
 *
 * The STAC walk stays as a fallback, so the viewer still works against a
 * `data/processed/` that predates the index.
 */
async function loadCatalog() {
  let index = null, indexUrl = null;
  for (const candidate of DATA_CANDIDATES) {
    try {
      indexUrl = new URL(`${candidate}/index.json`, location.href).href;
      index = await json(indexUrl);
      DATA = candidate;
      break;
    } catch { /* try the next layout */ }
  }
  if (index) {
    // Ground area per pixel by latitude, generated by raster.row_areas_m2. Without
    // it the readout cannot turn a pixel count into square kilometres, and it must
    // never work the value out for itself (CLAUDE.md #2), so its absence disables
    // the counting path rather than licensing a guess.
    state.areaTable = index.pixel_area_m2 || null;
    const out = {};
    for (const [id, layer] of Object.entries(index.layers)) {
      // One asset per layer: the map draws the whole archipelago from a single COG,
      // because OpenLayers cannot composite several GeoTIFF sources into one layer
      // (multiple `sources` become BANDS of one image, asserted to share an origin).
      // The per-island entries stay, carrying each island's bbox and published
      // figures — they are what a viewport-scoped readout will sum.
      out[id] = {
        title: layer.title,
        asset: resolve(indexUrl, layer.asset),
        stats: layer.stats || {},
        islands: layer.islands || {},
      };
    }
    return out;
  }
  return loadCatalogFromStac();
}

/** The original 64-request walk, kept as a fallback. */
async function loadCatalogFromStac() {
  let rootUrl = null, root = null;
  for (const candidate of DATA_CANDIDATES) {
    try {
      rootUrl = new URL(`${candidate}/catalog.json`, location.href).href;
      root = await json(rootUrl);
      DATA = candidate;
      break;
    } catch { /* try the next layout */ }
  }
  if (!root) throw new Error('no catalogue found in ' + DATA_CANDIDATES.join(' or '));
  const out = {};
  for (const link of root.links.filter((l) => l.rel === 'child')) {
    const colUrl = resolve(rootUrl, link.href);
    const col = await json(colUrl);
    const islands = {};
    let asset = null;
    for (const itemLink of col.links.filter((l) => l.rel === 'item')) {
      const itemUrl = resolve(colUrl, itemLink.href);
      const item = await json(itemUrl);
      // Every item now names the same archipelago asset, so the walk collapses to
      // one URL — taking it from whichever item we see first is correct, not a guess.
      asset = resolve(itemUrl, item.assets.data.href);
      islands[item.properties.island] = {
        stats: item.properties['sensisat:statistics'] || {},
        bbox: item.bbox,
      };
    }
    out[col.id] = {title: col.title, asset, stats: {}, islands};
  }
  return out;
}

/* -------------------------------------------------------------------- style */
/**
 * Colour expressions.
 *
 * One rule governs the shape of everything here: **only numbers may be style
 * variables; colours must be literals.** OpenLayers compiles `['var', x]` to a
 * `uniform float`, so putting a colour in a variable makes the fragment shader
 * fail to compile with "mismatching ternary operator operand types 'uniform highp
 * float' and 'const 4-component vector of float'" — and the map then renders
 * nothing at all, basemap included, with the failure only visible in the console.
 *
 * So the year window travels as two numbers (`lo`, `hi`) and the mode as a third
 * (`since`), and every branch below returns a literal vec4.
 */
const NONE = [0, 0, 0, 0];

function colourFor(name) {
  const def = LAYERS[name];
  const band = ['band', 1];

  if (def.kind === 'year' || def.kind === 'epoch') {
    const undated = def.kind === 'year'
      // "Built, year unknown" is a real third state, never a guess — but it cannot
      // belong to a period either, so the "added since" view must not claim it.
      ? [['==', band, UNDATED], ['case', ['==', ['var', 'since'], 1], NONE, C.undated]]
      : [];
    return ['case',
      ['==', band, 0], NONE,
      ...undated,
      ['<', band, ['var', 'lo']], NONE,
      ['>', band, ['var', 'hi']], NONE,
      ['==', ['var', 'since'], 1], C.added,
      C.built];
  }
  if (def.kind === 'binary') {
    return ['case', ['>', band, 0], C.green, NONE];
  }
  if (def.kind === 'percent') {
    return ['case', ['<=', band, 0], NONE,
      ['interpolate', ['linear'], band,
        1, [255, 245, 200, 0.75],
        30, [255, 190, 90, 0.85],
        60, [240, 120, 50, 0.92],
        100, [150, 25, 20, 1]]];
  }
  if (def.kind === 'trend') {
    return ['case', ['<=', band, 0], NONE,
      ['interpolate', ['linear'], band,
        1, [255, 245, 200, 0.7],
        1500, [255, 180, 70, 0.85],
        4000, [230, 100, 40, 0.92],
        8500, [140, 20, 20, 1]]];
  }
  if (def.kind === 'change') {
    return ['case',
      ['==', band, 1], C.gain,
      ['==', band, 2], C.loss,
      ['==', band, 11], [120, 190, 255, 0.85],
      ['==', band, 12], [255, 150, 150, 0.85],
      ['==', band, 10], [110, 130, 150, 0.35],
      NONE];
  }
  return ['case', ['>', band, 0], C.built, NONE];
}

/** Slider year -> WSF Tracker epoch. One rule, used by the shader and the readout. */
const toEpoch = (y) => Math.max(1, Math.min(20, Math.round((y - 2016) / 0.5)));

/** The epoch's published name, e.g. 2016-07. Falls back to the raw number. */
function epochLabel(e) {
  return state.catalog?.[state.layer]?.stats?.epoch_labels?.[e] ?? e;
}

/** Numeric style variables. Changing these re-renders on the GPU and fetches nothing. */
function variables() {
  const def = LAYERS[state.layer];
  const since = state.mode === 'since' ? 1 : 0;

  if (def.kind === 'year') {
    const enc = (y) => y - YEAR_OFFSET;
    return since
      ? {lo: enc(state.sinceYear) + 1, hi: UNDATED - 1, since}
      : {lo: 1, hi: enc(state.year), since};
  }
  if (def.kind === 'epoch') {
    return since
      ? {lo: toEpoch(state.sinceYear) + 1, hi: 20, since}
      : {lo: 1, hi: toEpoch(state.year), since};
  }
  return {lo: 0, hi: 255, since: 0};
}

/* ---------------------------------------------------------------------- map */
/**
 * Basemaps.
 *
 * Two of these are aerial photography, and that is the point: the fastest way to
 * tell whether a flagged pixel is a real building — or whether a real building was
 * missed — is to look at a photograph of the ground.
 *
 * **PNOA** is Spain's national orthophoto programme at 12–25 cm, an order of
 * magnitude sharper than the global satellite mosaics, and it is served natively
 * in EPSG:4326, so it needs no reprojection and stays crisp. It is also the exact
 * imagery M3's accuracy assessment will be interpreted from, which means checking
 * a layer against it here is checking it against the reference.
 *
 * **PNOA at the slider year** is the one worth knowing about. The historical
 * service publishes a separate layer per year, PNOA2004 to PNOA2024, so the
 * photograph underneath can follow the time slider: set the year to 2010 and you
 * are comparing what we say was built by 2010 against what the aeroplane saw in
 * 2010. Outside that range it clamps to the nearest available year and says so.
 *
 * Esri's global mosaic stays as the fallback that works outside Spain, which
 * matters the day this is pointed at anywhere else.
 */
/**
 * The cadastre bucketed unknown construction dates onto round years until 1980.
 * Measured (analysis 19), and the buckets are NOT all alike:
 *
 *   10 major buckets  1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1975, 1980
 *                     158,658 buildings — 33.8 % of every dated building. 1900
 *                     alone holds 25,971, the largest single year in the register.
 *    5 minor buckets  1905, 1915, 1925, 1935, 1945
 *                     4,471 buildings between them — 0.95 %. Statistically visible
 *                     (3–5x their neighbours) but practically invisible: 1915 adds
 *                     38 buildings to Santa Cruz de Tenerife, a city of 23,881.
 *
 * Only the major ones are called out. Warning about a year that moves 0.07 % of the
 * data would train the reader to ignore the warning that matters.
 *
 * After 1980 there is not one spike in 46 years, so dates from 1981 on are good to
 * the year. Before it they are good to about a decade — but 37 % of pre-1981
 * buildings do carry a genuine year, which is why the slider still moves a year at
 * a time rather than snapping to five.
 */
const CADASTRE_BUCKETED_UNTIL = 1980;
const CADASTRE_MAJOR_BUCKETS = new Set([1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1975, 1980]);

/**
 * PNOA flies the Canaries roughly every three years, not annually. Measured over
 * Gran Canaria: only these years return imagery; every other layer between 2004
 * and 2024 returns a blank white frame. Offering a year with no flight looked like
 * a working basemap that had gone white, which is worse than not offering it.
 */
const PNOA_YEARS = [2005, 2009, 2012, 2015, 2018, 2021, 2024];
const PNOA_FIRST_YEAR = PNOA_YEARS[0];
const PNOA_LAST_YEAR = PNOA_YEARS[PNOA_YEARS.length - 1];

const BASEMAPS = {
  light: {
    title: 'Map', kind: 'xyz',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',
    attributions: 'Tiles © Esri',
    // Light Gray Canvas is a GENERALISED basemap and stops at z16. Past that it
    // answers 200 with a 2,521-byte "Map data not yet available" image — the same
    // bytes at z17, z18 and z19 — so nothing errors and the map simply fills with
    // that notice. Declaring the real limit makes OpenLayers stretch the deepest
    // tile it has instead of asking for one that does not exist. Esri's own service
    // metadata is no help: it advertises LODs 0-23.
    maxZoom: 16,
  },
  pnoa: {
    title: 'Aerial', kind: 'wms',
    url: 'https://www.ign.es/wms-inspire/pnoa-ma',
    layers: 'OI.OrthoimageCoverage',
    attributions: 'PNOA © Instituto Geográfico Nacional de España',
  },
  pnoaYear: {
    title: 'Aerial by year', kind: 'wms-year',
    url: 'https://www.ign.es/wms/pnoa-historico',
    attributions: 'PNOA histórico © Instituto Geográfico Nacional de España',
  },
  satellite: {
    title: 'Satellite', kind: 'xyz',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    attributions: 'Imagery © Esri, Maxar, Earthstar Geographics',
    maxZoom: 19,     // verified: real imagery at z19 over Las Palmas, 14.8 KiB
  },
};

/** The nearest year PNOA actually flew — never a year that would come back blank. */
function pnoaYearFor(year) {
  const y = Math.round(year);
  return PNOA_YEARS.reduce((best, candidate) =>
    Math.abs(candidate - y) < Math.abs(best - y) ? candidate : best, PNOA_YEARS[0]);
}

function basemapSource(key) {
  const b = BASEMAPS[key];
  if (b.kind === 'xyz') {
    return new XYZ({url: b.url, attributions: b.attributions,
                    maxZoom: b.maxZoom ?? 19, crossOrigin: 'anonymous'});
  }
  // The most recent slot uses the CURRENT mosaic, not the historical PNOA2024
  // layer: measured, that layer sits 20 m east and 10 m north of every other year,
  // which would silently show different ground than the slider claims.
  const wantYear = pnoaYearFor(activeYear());
  const useCurrent = b.kind === 'wms-year' && wantYear >= PNOA_LAST_YEAR;
  const url = useCurrent ? 'https://www.ign.es/wms-inspire/pnoa-ma' : b.url;
  const layers = !b.kind.startsWith('wms-year') ? b.layers
    : useCurrent ? 'OI.OrthoimageCoverage' : `PNOA${wantYear}`;
  // No `serverType`. It makes OpenLayers send GeoServer vendor parameters and ask
  // for hi-dpi tiles, and IGN does not run GeoServer — every tile request then
  // fails, with nothing in the console to say so.
  const source = new TileWMS({
    url: b.kind === 'wms-year' ? url : b.url,
    attributions: b.attributions, crossOrigin: 'anonymous',
    params: {LAYERS: layers, FORMAT: 'image/jpeg'},
    transition: 250, ratio: 1,
  });
  source.on('tileloaderror', () => {
    el('basemap-note').textContent = 'Aerial imagery unavailable here — PNOA covers Spain only.';
  });
  return source;
}

/** The basemap layer, looked up from the map rather than held in a variable. */
function baseLayer() {
  return map.getLayers().item(0);
}

/** Which basemap is selected — read from the lit button, the thing the user can see. */
function activeBasemap() {
  return document.querySelector('#basemaps button.on')?.dataset.base ?? 'light';
}

/** The year the aerial photograph should show: whatever the slider points at. */
function activeYear() {
  const def = LAYERS[state.layer];
  if (!def || !['year', 'epoch', 'trend'].includes(def.kind)) return PNOA_LAST_YEAR;
  return sliderYear();
}

/** Keep the year-following aerial in step with the slider. */
function syncBasemapYear() {
  if (activeBasemap() !== 'pnoaYear') return;
  const wanted = `PNOA${pnoaYearFor(activeYear())}`;
  const source = baseLayer().getSource();
  if (source?.getParams && source.getParams().LAYERS !== wanted) {
    source.updateParams({LAYERS: wanted});
  }
  const asked = Math.round(activeYear());
  const shown = pnoaYearFor(asked);
  el('basemap-note').textContent = shown === asked
    ? `Aerial photograph from ${shown}.`
    : `Aerial photograph from ${shown} — the nearest PNOA flight. The Canaries are `
      + `photographed about every three years (${PNOA_YEARS.join(', ')}), not annually.`;
}

/**
 * Say so when the view has gone deeper than the basemap has pictures for.
 *
 * Without this the map looks broken: the layer draws correctly over a background
 * that has quietly stopped carrying information, and there is nothing on screen to
 * say which of the two is at fault. Being stretched is the right behaviour — it
 * beats a wall of "Map data not yet available" — but only if the reader is told.
 */
function syncBasemapNote() {
  if (activeBasemap() === 'pnoaYear') { syncBasemapYear(); return; }
  const b = BASEMAPS[activeBasemap()];
  const deeper = Object.values(BASEMAPS)
    .filter((o) => o !== b && (o.maxZoom ?? 99) > (b?.maxZoom ?? 99))
    .map((o) => o.title);
  el('basemap-note').textContent =
    b?.maxZoom != null && map.getView().getZoom() > b.maxZoom + 0.5
      ? `The ${b.title} basemap has no more detail at this zoom and is being stretched.`
        + (deeper.length
            ? ` ${deeper.slice(0, -1).join(', ')}${deeper.length > 1 ? ' and ' : ''}`
              + `${deeper[deeper.length - 1]} go deeper.`
            : '')
      : '';
}

const base = new TileLayer({source: basemapSource('light')});

/**
 * The view is EPSG:4326 — the projection our COGs are already in — and NOT the
 * usual EPSG:3857. This is forced, not a preference: a WebGLTileLayer cannot
 * reproject, so a GeoTIFF source whose projection differs from the view simply
 * never renders, with no error to say why. The basemap is the piece that gets
 * reprojected instead, which an ordinary raster TileLayer does support.
 */
const map = new OLMap({
  target: 'map', layers: [base],
  view: new View({projection: 'EPSG:4326', center: [-15.6, 28.0], zoom: 9, maxZoom: 19}),
});
let dataLayer = null;

async function showLayer() {
  const entry = state.catalog[state.layer];
  if (!entry?.asset) { status(`no data published for ${state.layer}`, true); return; }
  status('loading raster…');
  // Before the raster: the figures come from index.json, which is already in memory,
  // so they never needed to wait for it. Leaving them alone until the COG resolved
  // meant the PREVIOUS layer's number sat under the new layer's name for about a
  // second — a figure from one layer displayed beside another, which is the kind of
  // stale-number problem this project spends most of its gates preventing.
  renderLegend();
  renderReadout(scope());

  const def = LAYERS[state.layer];
  const bandIndex = def.kind === 'trend' ? def.epochs.indexOf(state.year) + 1 : 1;

  const source = new GeoTIFF({
    sources: [{url: entry.asset, bands: [bandIndex || 1], nodata: 0}],
    normalize: false, interpolate: false, convertToRGB: false,
  });
  const layer = new WebGLTileLayer({
    source, style: {color: colourFor(state.layer), variables: variables()}, opacity: 0.92,
  });

  if (dataLayer) map.removeLayer(dataLayer);
  dataLayer = layer;
  map.addLayer(layer);

  source.on('error', (e) => status(`raster error: ${e.error?.message || e.message}`, true));
  try {
    const view = await source.getView();
    map.getView().fit(entry.bbox ?? view.extent, {padding: [30, 30, 30, 30], duration: 350});
    status(`${def.title} — Canary Islands`);
  } catch (err) {
    console.error(err);
    status(`could not read the raster: ${err.message}`, true);
  }
  renderLegend();
  renderReadout(scope());
  // fit() animates, so its moveend arrives on its own; this covers the case where
  // the view does not move at all because the new layer has the same extent.
  scheduleScope(400);
}

function restyle() {
  if (!dataLayer) return;
  const def = LAYERS[state.layer];
  if (def.kind === 'trend') { showLayer(); return; }   // a different band, so a new read
  dataLayer.updateStyleVariables(variables());
  renderReadout(scope());
}

/* ------------------------------------------------------------------ panel */
/** Whichever year the slider is currently pointing at, given the mode. */
function sliderYear() {
  const def = LAYERS[state.layer];
  return state.mode === 'since' && def.kind !== 'trend' ? state.sinceYear : state.year;
}

/** Warn when the slider sits in the part of the cadastre that was bucketed. */
function precisionNote() {
  if (state.layer !== 'buildings-dated') return '';
  const y = Math.round(sliderYear());
  if (y > CADASTRE_BUCKETED_UNTIL) return '';
  if (CADASTRE_MAJOR_BUCKETS.has(y)) {
    return `⚠ ${y} is one of the ten years the cadastre used for "old, date unknown". `
         + `Together they hold a third (33.8 %) of all dated buildings, so read this frame as `
         + `"by about ${y}" rather than as ${y} exactly.`;
  }
  return `Before ${CADASTRE_BUCKETED_UNTIL} the cadastre rounded many unknown dates onto `
       + `whole decades, so this frame is reliable to roughly a decade. Years that are `
       + `not round are genuine.`;
}

function modeNote() {
  if (state.mode !== 'since') return '';
  return `Showing only what appeared after ${state.sinceYear}. Two states side by side hide `
       + `change: Gran Canaria grew ${FACTS.gc_growth_1995_2015_pct} % between 1995 and 2015 and the two maps look identical.`;
}

function renderLegend() {
  const def = LAYERS[state.layer];
  const key = (colour, label) =>
    `<div class="key"><span class="sw" style="background:rgba(${colour[0]},${colour[1]},${colour[2]},${colour[3]})"></span><span>${label}</span></div>`;
  const ramp = (stops, label) =>
    `<div class="key"><span class="ramp" style="background:linear-gradient(90deg,${stops})"></span></div><div class="cap">${label}</div>`;

  let html = '';
  if (def.kind === 'year' || def.kind === 'epoch') {
    if (state.mode === 'since') {
      html += key(C.added, `Appeared after ${state.sinceYear}`);
      // The undated class is deliberately absent here: a pixel with no year cannot
      // be placed in a period, so the change view must not imply that it can.
      if (def.kind === 'year') html += `<div class="cap">Undated pixels are hidden — they cannot be assigned to a period.</div>`;
    } else {
      html += key(C.built, `Built by ${state.year}`);
      if (def.kind === 'year') html += key(C.undated, 'Built, year unknown');
    }
  } else if (def.kind === 'binary') {
    html += key(C.green, 'Greenhouse parcel');
  } else if (def.kind === 'percent') {
    html += ramp('rgba(255,245,200,.8),rgba(255,190,90,.9),rgba(240,120,50,.95),rgba(150,25,20,1)', '1 % → 100 % of the pixel sealed');
  } else if (def.kind === 'trend') {
    html += ramp('rgba(255,245,200,.8),rgba(255,180,70,.9),rgba(230,100,40,.95),rgba(140,20,20,1)', `m² built per cell, ${state.year}`);
  } else if (def.kind === 'change') {
    html += key(C.gain, 'New built-up cover') + key(C.loss, 'Loss of cover')
         + key([110, 130, 150, 0.6], 'Unchanged built-up');
  }
  el('legend').innerHTML = html;
}

/**
 * Format an area for display, in the READER's number convention.
 *
 * Raw JavaScript prints 2.343 and 7344.65, which is the English convention and
 * ambiguous everywhere that uses "." to group thousands — Spain and most of the
 * continent, which is to say much of this map's audience. A Spanish planner reading
 * "2.343 km²" sees two thousand.
 *
 * The locale must be `navigator.languages`, NOT omitted. Measured in Chrome with
 * navigator.language = "es-ES": `Intl.NumberFormat(undefined)` resolves to en-US,
 * because the runtime default follows the browser's UI language rather than the
 * user's content preferences. Passing the preference list explicitly is what
 * actually honours it.
 *
 * Two decimals, always. These are square kilometres of an island, so a third
 * decimal is 1000 m² of precision nobody is reading. The one consequence worth
 * knowing: a change smaller than 0.005 km² prints as 0, which only the loss layer
 * can produce.
 */
const area = (n) => n == null || !isFinite(n) ? '—'
  : new Intl.NumberFormat(navigator.languages, {maximumFractionDigits: 2}).format(n);

/* ------------------------------------------------- what is on screen, counted */
/**
 * Full-resolution handles, one per published file.
 *
 * Opening a COG costs one range request for its header, and every window read
 * afterwards reuses it — so this map is what stops a pan from re-reading the header
 * each time. `getImage(0)` is deliberate: image 0 is the full-resolution image and
 * 1..n are the overviews, and the readout must never count an overview (see
 * count.js for the 104.3 -> 3,310.3 km2 this avoids).
 */
const images = new Map();
const fullResImage = (url) => {
  if (!images.has(url)) images.set(url, fromUrl(url).then((t) => t.getImage(0)));
  return images.get(url);
};

/**
 * Decode workers.
 *
 * A COG is stored in compressed 1024 x 1024 blocks, so even a small window inflates
 * more than a million pixels, and a view covering most of an island inflates tens of
 * millions. On the main thread that is a visibly frozen page — measured here by
 * freezing it. geotiff.js takes a worker pool and does the inflating off-thread.
 *
 * Measured worth on the published mosaic, a 25 km view over Tenerife: 533 and
 * 601 ms with the pool against 616, 878 and 1,013 ms without. geotiff.js embeds the
 * worker source and builds it from a Blob, so it survives bundling — which is not
 * obvious, and is why the numbers are written down here.
 *
 * Created lazily and guarded: worker construction is the kind of thing a bundler or
 * a strict CSP can break, and a readout that is merely slower is better than one
 * that throws. If it cannot be built we decode in place, as before.
 */
let decodePool;
function pool() {
  if (decodePool === undefined) {
    try { decodePool = new Pool(); } catch (err) { console.warn('no decode pool', err); decodePool = null; }
  }
  return decodePool || undefined;
}

/**
 * The pixel window covering a map extent, clipped to the file.
 *
 * Returns null when the view and the file share no ground — which is a real answer
 * (the sea holds no buildings), not a failure. `north` comes back because turning
 * pixels into square kilometres needs the latitude of the window's top EDGE, and
 * recovering it later from the extent rather than from the window would reintroduce
 * exactly the fractional-window offset of CLAUDE.md #25.
 */
function windowFor(image, extent) {
  const [w, s, e, n] = image.getBoundingBox();
  const width = image.getWidth(), height = image.getHeight();
  const px = (e - w) / width, py = (n - s) / height;

  const left = Math.max(0, Math.floor((extent[0] - w) / px));
  const right = Math.min(width, Math.ceil((extent[2] - w) / px));
  const top = Math.max(0, Math.floor((n - extent[3]) / py));
  const bottom = Math.min(height, Math.ceil((n - extent[1]) / py));
  if (right <= left || bottom <= top) return null;

  return {left, top, right, bottom, pixelDeg: py, north: n - top * py,
          width: right - left, height: bottom - top,
          pixels: (right - left) * (bottom - top)};
}

/**
 * The year or epoch keys to report, taken from what the build published.
 *
 * Emitting the published keys rather than a range of this file's own choosing is
 * what lets the counted answer and the summed answer be compared key by key — and
 * it is the difference between a readout that agrees with the page and one that
 * merely looks similar.
 */
function seriesKeys(entry, def) {
  const s = entry.stats || {};
  const nums = (o) => Object.keys(o || {}).map(Number).sort((a, b) => a - b);
  if (def.kind === 'year') return {years: nums(s.extent_by_year)};
  if (def.kind === 'epoch') return {epochs: nums(s.extent_by_epoch)};
  return {};
}

/**
 * Recompute what the readout describes, for the view as it now stands.
 *
 * Two regimes (count.js holds the choice and the arithmetic). Small views read the
 * real pixels; large ones sum the published figures of the islands they touch. The
 * caption says which, because the number genuinely means different things.
 *
 * `token` guards against a slow read landing after a faster, later one: panning
 * fires several of these, and the answer that arrives last is not necessarily the
 * answer to the view the user is looking at.
 */
let scopeToken = 0;
let moveTimer = null;

async function updateScope() {
  const token = ++scopeToken;
  const entry = state.catalog?.[state.layer];
  if (!entry) return;
  const def = LAYERS[state.layer];
  const extent = map.getView().calculateExtent(map.getSize());
  const names = islandsInView(extent, entry.islands || {});
  const total = Object.keys(entry.islands || {}).length;

  const settle = (scope) => {
    if (token !== scopeToken) return;      // a later view has already superseded this
    state.scope = scope;
    renderReadout(scope);
  };
  const zero = () => (FAR_ONLY_KINDS.has(def.kind) ? {} : emptyStats(def.kind, seriesKeys(entry, def)));
  const far = () => ({
    regime: 'far',
    label: describe('far', names, total),
    stats: names.length ? sumStats(names.map((n) => entry.islands[n].stats)) : zero(),
  });

  // No table means no honest way to turn pixels into square kilometres, so the
  // counting path is simply unavailable — never approximated.
  if (FAR_ONLY_KINDS.has(def.kind) || !state.areaTable) { settle(far()); return; }

  // If the count is quick, the readout updates once and the reader sees no
  // intermediate state. If it is not, the island figure goes up rather than leaving
  // the PREVIOUS view's number sitting there — it is correct, merely coarser, and
  // its caption says which islands it covers. The counted answer then replaces it.
  const slow = setTimeout(() => settle(far()), 250);
  try {
    const image = await fullResImage(entry.asset);
    if (token !== scopeToken) { clearTimeout(slow); return; }
    const win = windowFor(image, extent);
    if (!win) {
      clearTimeout(slow);
      settle({regime: 'near', label: describe('near', names, total), stats: zero()});
      return;
    }
    // The budget is in BLOCKS because that is the unit a COG is read in — a window
    // smaller than one block still costs a whole one. blockSpan() measures the
    // window's SIZE, never its alignment, so panning at a fixed zoom cannot change
    // which regime answers (see count.js).
    const tile = {width: image.getTileWidth(), height: image.getTileHeight()};
    if (regimeFor(def.kind, blockSpan(win, tile)) !== 'near') {
      clearTimeout(slow);
      settle(far());
      return;
    }

    // Band 1 for every layer with a near path; only density-trend is multi-band and
    // it is far-only. geotiff.js counts samples from 0, OpenLayers from 1.
    const [values] = await image.readRasters({
      window: [win.left, win.top, win.right, win.bottom], samples: [0], pool: pool(),
    });
    clearTimeout(slow);
    const areas = rowAreas(state.areaTable, win);
    const hist = areaHistogram(values, {width: win.width, height: win.height, areas});
    settle({regime: 'near', label: describe('near', names, total),
            stats: statsFromHistogram(hist, {kind: def.kind, ...seriesKeys(entry, def)})});
  } catch (err) {
    // A failed read must not blank the number. The island sums are honest because
    // the caption then names the islands rather than claiming to describe the screen.
    clearTimeout(slow);
    console.error(err);
    settle(far());
  }
}

/** Panning fires a burst of these; only the view it settles on is worth reading. */
function scheduleScope(delay = 150) {
  clearTimeout(moveTimer);
  moveTimer = setTimeout(updateScope, delay);
}

/**
 * What the readout is describing, right now and synchronously.
 *
 * Until a view has been measured this is the whole archipelago, which is both true
 * at first paint and instantly available — the figures are already in index.json.
 * updateScope() then replaces it. Every caption below reads `label` and never asks
 * how the number was reached.
 */
function scope() {
  if (state.scope) return state.scope;
  const layer = state.catalog?.[state.layer];
  return {regime: 'far', label: 'all eight islands', stats: layer?.stats || {}};
}


function renderReadout(entry) {
  const def = LAYERS[state.layer];
  const s = entry?.stats || {};

  // The trend layer's number is per epoch, and the loss layer's is per period —
  // neither has a single "how much is there" figure, so each says what it has.
  if (def.kind === 'trend' && s.surface_km2) {
    const now = s.surface_km2[state.year], first = s.surface_km2[def.epochs[0]];
    const growth = first ? Math.round(100 * (now / first - 1)) : null;
    el('readout').innerHTML = `<div class="big">${area(now)} km²</div>`
      + `<div class="cap">built surface in ${state.year}`
      + (growth == null ? '' : ` · ${growth >= 0 ? '+' : ''}${growth} % since ${def.epochs[0]}`)
      + ` · ${s.observed?.[state.year] ?? ''}</div>`;
    return;
  }
  if (def.kind === 'change' && s.change_km2) {
    const rows = Object.entries(s.change_km2).map(([period, v]) =>
      `<div class="cap">${period}: <b>+${area(v.new_cover_km2)}</b> km² new, <b>−${area(v.loss_of_cover_km2)}</b> km² lost</div>`).join('');
    el('readout').innerHTML = `<div class="cap">Built-up change, ${entry.label}</div>${rows}`;
    return;
  }

  // A number that does not move while the map visibly does reads as a bug, so the
  // time-varying layers report the extent at the year on the slider, not their
  // whole-island total. Undated pixels are not in these series — they are built but
  // cannot be placed in a year — so the caption says so rather than quietly
  // dropping them.
  if (def.kind === 'year' && s.extent_by_year) {
    const yrs = Object.keys(s.extent_by_year).map(Number);
    const clamp = (v) => Math.min(Math.max(v, Math.min(...yrs)), Math.max(...yrs));
    // "Added since" is a SUBTRACTION of two cumulative totals, and the readout has to
    // do it too. The map in this mode draws only what appeared after the slider year;
    // a readout still showing the running total describes a different picture from
    // the one on screen, which is the whole thing C4 exists to stop. Both regimes get
    // it free: the series is already in memory, near or far.
    if (state.mode === 'since') {
      const added = addedSince(s.extent_by_year, state.sinceYear);
      el('readout').innerHTML = `<div class="big">${area(added)} km²</div>`
        + `<div class="cap">${def.title.toLowerCase()} appearing after ${state.sinceYear}, `
        + `${entry.label} · undated ground is excluded, it cannot be placed in a period</div>`;
      return;
    }
    const y = clamp(state.year);
    const now = s.extent_by_year[y];
    const undated = s.undated_km2 ?? s['pre-2016, undated'];
    // VISIBLE, not merely non-zero. area() prints two decimals, so a scope holding
    // 0.000088 km² of undated ground produced "plus 0 km² built but undated" — a
    // clause that says nothing while looking like a figure. The threshold is the
    // smallest value that prints as anything other than zero.
    const showUndated = undated != null && undated >= 0.005;
    el('readout').innerHTML = `<div class="big">${area(now)} km²</div>`
      + `<div class="cap">${def.title.toLowerCase()} by ${state.year}, ${entry.label}`
      + (showUndated ? ` · plus ${area(undated)} km² built but undated` : '') + '</div>';
    return;
  }
  if (def.kind === 'epoch' && s.extent_by_epoch) {
    if (state.mode === 'since') {
      // Within era-b only. Epoch 1 is the July-2016 baseline, so "since epoch 1" means
      // everything built after it — a subtraction inside ONE era, never across the
      // 2015/2016 seam, which the two layers share as a baseline (decision 13).
      const from = toEpoch(state.sinceYear);
      const added = addedSince(s.extent_by_epoch, from);
      el('readout').innerHTML = `<div class="big">${area(added)} km²</div>`
        + `<div class="cap">${def.title.toLowerCase()} appearing after `
        + `${epochLabel(from)}, ${entry.label}</div>`;
      return;
    }
    const e = toEpoch(state.year);
    const label = epochLabel(e);
    el('readout').innerHTML = `<div class="big">${area(s.extent_by_epoch[e])} km²</div>`
      + `<div class="cap">${def.title.toLowerCase()} by ${label}, ${entry.label}`
      + (s.greenhouse_removed_km2 ? ` · ${area(s.greenhouse_removed_km2)} km² of greenhouses removed` : '')
      + '</div>';
    return;
  }

  const km2 = s.footprint_km2 ?? s.area_km2 ?? s.sealed_km2 ?? null;
  let extra = '';
  if (s['pre-2016, undated'] != null) extra = `${s['dated_share_pct']} % of it carries a year`;
  else if (s.greenhouse_removed_km2 != null) extra = `${area(s.greenhouse_removed_km2)} km² of greenhouses removed`;
  else if (s.survey_year) extra = `surveyed ${s.survey_year}`;
  el('readout').innerHTML = km2 == null ? ''
    : `<div class="big">${area(km2)} km²</div><div class="cap">${def.title.toLowerCase()}, ${entry.label}${extra ? ' · ' + extra : ''}</div>`;
}

function syncTimeControls() {
  const def = LAYERS[state.layer];
  const timed = ['year', 'epoch', 'trend'].includes(def.kind);
  el('time-controls').style.display = timed ? '' : 'none';
  el('layer-note').textContent = def.note || '';
  el('seam-note').textContent = def.seam || '';
  if (!timed) { renderLegend(); return; }

  const slider = el('year');
  if (def.kind === 'trend') {
    slider.min = 0; slider.max = def.epochs.length - 1; slider.step = 1;
    slider.value = def.epochs.indexOf(state.year);
    el('tick-min').textContent = def.epochs[0];
    el('tick-max').textContent = def.epochs.at(-1);
  } else if (def.kind === 'epoch') {
    // WSF Tracker runs twice a year, so a whole-year step reaches only half the
    // epochs — and rounding 2016.5 up put epoch 1, the July 2016 baseline this
    // layer's own note describes, out of reach entirely.
    slider.min = def.min; slider.max = def.max; slider.step = 0.5;
    slider.value = sliderYear();
    el('tick-min').textContent = epochLabel(toEpoch(def.min));
    el('tick-max').textContent = epochLabel(toEpoch(def.max));
  } else {
    slider.min = Math.ceil(def.min); slider.max = Math.floor(def.max); slider.step = 1;
    slider.value = sliderYear();
    el('tick-min').textContent = Math.ceil(def.min);
    el('tick-max').textContent = Math.floor(def.max);
  }
  // A half-year reads as "2016.5" unless it is named, which is what the epoch
  // labels published with the layer are for.
  el('year-out').textContent = def.kind === 'epoch'
    ? epochLabel(toEpoch(sliderYear())) : sliderYear();
  el('mode-note').textContent = modeNote();
  el('precision-note').textContent = precisionNote();
}

/* ------------------------------------------------------------------- wiring */
function setLayer(name) {
  state.layer = name;
  // The previous layer's measurement describes the previous layer. Clearing it makes
  // scope() fall back to this layer's published archipelago total — true, instant,
  // and replaced as soon as the view is measured. Keeping it would put one layer's
  // number under another layer's name, which is the defect commit 8631160 fixed in
  // its other form.
  state.scope = null;
  const def = LAYERS[name];
  if (def.kind === 'trend') state.year = def.start;
  else if (def.kind === 'year' || def.kind === 'epoch') state.year = Math.floor(def.start ?? def.max);
  state.sinceYear = def.kind ? Math.floor(((def.min ?? 1900) + (def.max ?? 2020)) / 2) : 2000;
  syncTimeControls();
  showLayer();
}

function init(catalog) {
  state.catalog = catalog;
  const layerSel = el('layer');

  // The readout follows the map. `moveend` rather than `change:center` because a
  // pan fires hundreds of the latter, and the only view worth measuring is the one
  // the user stops on; the debounce then absorbs a flick of the wheel.
  map.on('moveend', () => { scheduleScope(); syncBasemapNote(); });

  layerSel.innerHTML = Object.entries(LAYERS)
    .filter(([id]) => catalog[id])
    .map(([id, d]) => `<option value="${id}">${d.title}</option>`).join('');
  layerSel.value = state.layer;

  const basemapBox = el('basemaps');
  basemapBox.innerHTML = Object.entries(BASEMAPS)
    .map(([k, b], i) => `<button data-base="${k}"${i === 0 ? ' class="on"' : ''}>${b.title}</button>`).join('');
  basemapBox.querySelectorAll('button').forEach((b) => {
    b.onclick = () => {
      basemapBox.querySelectorAll('button').forEach((x) => x.classList.remove('on'));
      b.classList.add('on');
      state.basemap = b.dataset.base;
      el('basemap-note').textContent = '';
      baseLayer().setSource(basemapSource(b.dataset.base));
      syncBasemapNote();
      map.renderSync();
    };
  });

  layerSel.onchange = () => setLayer(layerSel.value);

  // Scoped to #viewmodes, NOT to `.modes button`. The basemap switcher reuses the
  // `.modes` class for its styling, so the broad selector matched those buttons too
  // and this loop overwrote their click handlers — clicking "Aerial" ran the
  // view-mode handler, which lit the button, left the basemap untouched, and set
  // state.mode to undefined. Style classes must never be used as behaviour selectors.
  const viewModes = el('viewmodes');
  viewModes.querySelectorAll('button').forEach((b) => {
    b.onclick = () => {
      viewModes.querySelectorAll('button').forEach((x) => x.classList.remove('on'));
      b.classList.add('on');
      state.mode = b.dataset.mode;
      syncTimeControls(); restyle(); renderLegend();
    };
  });

  el('year').oninput = (e) => {
    const def = LAYERS[state.layer];
    const value = def.kind === 'trend' ? def.epochs[+e.target.value] : +e.target.value;
    // The slider means "up to this year" in state mode and "since this year" in
    // change mode. One control, because the user is always pointing at one year.
    if (state.mode === 'since' && def.kind !== 'trend') state.sinceYear = value;
    else state.year = value;
    // syncTimeControls names epochs; the live handler has to do the same or the
    // label reverts to a bare "2016.5" as soon as the slider moves.
    el('year-out').textContent = def.kind === 'epoch' ? epochLabel(toEpoch(value)) : value;
    el('mode-note').textContent = modeNote();
    el('precision-note').textContent = precisionNote();
    syncBasemapYear();
    restyle(); renderLegend();
  };

  el('play').onclick = () => {
    const btn = el('play');
    if (state.playing) { clearInterval(state.playing); state.playing = null; btn.classList.remove('on'); btn.innerHTML = '&#9658;'; return; }
    btn.classList.add('on'); btn.innerHTML = '&#10073;&#10073;';
    const slider = el('year');
    state.playing = setInterval(() => {
      let v = +slider.value + 1;
      if (v > +slider.max) v = +slider.min;
      slider.value = v; slider.dispatchEvent(new Event('input'));
    }, 130);
  };

  setLayer(state.layer);

  // Exposed for debugging and for driving the viewer from a test harness. The
  // module scope is otherwise closed, so there is no other way to inspect what the
  // map is actually doing from outside.
  window.sensisat = {map, state, LAYERS, showLayer, restyle, updateScope, scope,
                     get layer() { return dataLayer; }};
}

(async () => {
  try {
    // One request. statistics/layers.json used to be fetched here and assigned to
    // state.stats, which nothing ever read — C2 moved those figures into index.json.
    // It was 10 KiB on the critical path for no consumer.
    init(await loadCatalog());
  } catch (err) {
    status(`could not load the catalogue: ${err.message}`, true);
    console.error(err);
  }
})();
