/**
 * What is on screen, as a number.
 *
 * The readout must describe **what the map is showing at that moment** — the whole
 * archipelago, one island, a city, a neighbourhood — and read `0 km²` over open sea.
 * This module holds every decision that answer needs, and nothing else: no
 * OpenLayers import, no DOM, all input injected. That is deliberate. It means
 * `node --test` can reach it without a browser, and it means the arithmetic lives
 * in one place the way `stats.zonal()` does on the Python side (decision 7).
 *
 * ## Two regimes, and why there have to be two
 *
 * The obvious implementation — count the pixels the map is drawing — is wrong when
 * zoomed out, and wrong by a factor nobody would guess. A Cloud-Optimised GeoTIFF
 * ships pre-made coarse copies of itself ("overviews") so a zoomed-out map does not
 * have to read every pixel. Ours are built with `mode` resampling and `nodata`
 * excluded, which means a coarse pixel says "built" if **any** of its children is
 * built. That is the right rule for DRAWING — otherwise villages disappear as you
 * zoom out — and a catastrophe for COUNTING, because counting then assumes every
 * one of those children is full. Measured on `buildings-dated`:
 *
 *     full resolution   104.3 km²   <- the published figure
 *     zoomed out  8x  1,026.7 km²
 *     zoomed out 32x  3,310.3 km²
 *
 * and no correction factor exists, because the error depends on how clustered the
 * buildings are: at 32x it is 23.9x on dense Gran Canaria against 101.7x on
 * scattered El Hierro. See `tests/test_coverage.py`, which pins both.
 *
 * So:
 *
 * **Near** — small enough views read the raster at FULL resolution and count it.
 * Verified against `rasterio` over real HTTP at four scales (1,779 / 28,039 /
 * 140,164 / 339,060 pixels): identical every time. A browser count is therefore not
 * a second implementation of anything — it reads the same bytes and applies the same
 * rule as the shader.
 *
 * **Far** — bigger views sum the published per-island figures for the islands the
 * view touches. Free (they are already in `index.json`), instant, exact, per-year.
 *
 * The honest cost is that the number changes MEANING at the crossover: near it is
 * "what is in view", far it is "these whole islands". The caption has to say which,
 * which is why `describe()` returns a label and not just a number.
 *
 * ## One pass gives every year at once
 *
 * The near path does not count "pixels built by 2004". It accumulates a weighted
 * histogram: bin `v` holds the total ground area of the pixels holding value `v`.
 * Since our rasters encode the YEAR a pixel was first built, the running total of
 * bins 1..n IS `extent_by_year`, for every year, from one pass. Moving the slider
 * then costs nothing and fetches nothing — the same property that makes the map
 * itself server-free.
 *
 * ## Pixels are degrees, not metres
 *
 * A "10 m" pixel is 8.983e-05 degrees on both axes, which at 28°N is 9.98 m
 * north-south but only 8.81 m east-west — about 88 m², not 100 (CLAUDE.md #2).
 * Counting pixels and multiplying overstates area by ~12 %. So nothing here
 * multiplies by a nominal pixel size: `rowAreas()` looks the true value up in a
 * table generated by `raster.row_areas_m2` and shipped with the data.
 */

/* ----------------------------------------------------------- the encoding */
/**
 * The contract with `sensisat/encoding.py`. Defined HERE and imported by app.js so
 * there is one definition in JavaScript rather than two that can drift apart.
 */
export const YEAR_OFFSET = 1899;   // stored value = year - 1899
export const UNDATED = 255;        // built, year unknown — a real third state
export const NOT_BUILT = 0;

/* ------------------------------------------------------------ the crossover */
/**
 * How much the near path is allowed to read, in BLOCKS.
 *
 * A Cloud-Optimized GeoTIFF is stored in fixed square tiles, and a reader cannot
 * fetch less than a whole one: our archipelago mosaics use 1024 x 1024, so the
 * smallest possible read is 1,048,576 pixels no matter how small the view. That is
 * why the first attempt at this constant — a budget in window pixels — described
 * the wrong thing entirely. Measured on the published mosaic: a 3.2 km view (82,364
 * pixels, 4 blocks) and a 12.6 km view (1,317,818 pixels, 6 blocks) cost the SAME
 * ~280 ms, while the pixel counts differ sixteenfold. A 50 km view is 35 blocks and
 * ~2.5 s.
 *
 * So the budget is blocks, the unit the cost is actually paid in. At 1024 and the
 * 10 m grid, 8 blocks is roughly a 30 km view — most of an island — which is the
 * range where a reader wants a number that follows the map. Beyond it the published
 * island totals answer instantly and exactly, and counting would buy nothing but
 * seconds of waiting.
 *
 * The budget is measured against `blockSpan()`, which ignores alignment, so the
 * worst real read is about one extra row and column of blocks — near 15 rather than
 * 8, or roughly 1.1 s. That slack is the price of a regime that does not change
 * when you pan.
 *
 * This is NOT a latency cliff, because the readout no longer waits for it: the far
 * answer is shown immediately and the counted one replaces it when it arrives.
 */
export const NEAR_MAX_BLOCKS = 8;

/**
 * The size of a window in blocks — what decides the regime.
 *
 * **Deliberately independent of where the window sits.** A read that straddles a
 * block boundary genuinely costs more than one that does not, so the honest
 * estimate of cost would count the blocks actually touched. Using that to CHOOSE
 * the regime was a mistake, and a visible one: at about 25 km a window spans
 * roughly 2.8 x 1.95 blocks, which touches 3 x 2 = 6 when it happens to line up and
 * 4 x 3 = 12 when it does not. Panning a few hundred metres at a fixed zoom crossed
 * the budget, and the readout flipped between counting the view and reporting the
 * whole of Gran Canaria — the same picture answered two different ways depending on
 * nothing the reader can see.
 *
 * So the decision uses `ceil(width / tile)` — the number of blocks a window of this
 * SIZE spans — which cannot change while the zoom holds still. The true read may
 * touch one more row and column than this; the budget is set knowing that, and a
 * stable answer is worth more than a tight cost estimate.
 */
export function blockSpan({width, height}, tile) {
  return Math.max(1, Math.ceil(width / tile.width))
       * Math.max(1, Math.ceil(height / tile.height));
}


/**
 * Layers whose near path is not implemented, and which therefore always report the
 * far way. Not an oversight in either case:
 *
 * - `trend` is on GHSL's native 3-arcsecond grid, not the shared 10 m grid, and its
 *   values are square metres per cell — so summing them needs that grid's own cell
 *   accounting, not this one's. Its own statistics say as much (`why_native`).
 * - `change` reports gain and loss per period, which is four numbers rather than
 *   one, and its periods live in separate bands.
 */
export const FAR_ONLY_KINDS = new Set(['trend', 'change']);

/**
 * Which regime answers this view.
 *
 * `blocks` is the window's size in blocks, from `blockSpan()`.
 */
export function regimeFor(kind, blocks) {
  if (FAR_ONLY_KINDS.has(kind)) return 'far';
  return blocks <= NEAR_MAX_BLOCKS ? 'near' : 'far';
}

/* ------------------------------------------------------------- ground area */
/**
 * Ground area of one pixel at a latitude, in m², from a shipped table.
 *
 * The table is `{lat0, step, values}` — `values[i]` is the area at
 * `lat0 + i * step` — generated by `raster.row_areas_m2` and downsampled, because
 * the quantity varies with `cos(latitude)` and so is smooth: over the archipelago's
 * 27.5°–29.6° span it moves only 2 %, and linear interpolation between samples
 * 0.1° apart is accurate to roughly one part in three million.
 *
 * Shipping it rather than computing it is the point. The moment JavaScript works
 * out its own pixel areas there are two definitions of ground area in the project,
 * and the ~12 % error of CLAUDE.md #2 is exactly the kind that looks plausible.
 */
export function pixelAreaM2(table, lat) {
  const {lat0, step, values} = table;
  const x = (lat - lat0) / step;
  if (!isFinite(x)) throw new Error(`pixelAreaM2: latitude ${lat} is not a number`);
  if (x <= 0) return values[0];
  if (x >= values.length - 1) return values[values.length - 1];
  const i = Math.floor(x);
  const t = x - i;
  return values[i] * (1 - t) + values[i + 1] * t;
}

/**
 * Per-row pixel areas for a window, in m². Shape is one value per raster row.
 *
 * `north` is the latitude of the window's top EDGE and `pixelDeg` its row height,
 * so row `r` is sampled at its centre — the same half-pixel offset
 * `raster.row_areas_m2` uses. Getting that wrong biases every row by half a pixel
 * in the same direction, which is precisely the sort of error that survives
 * inspection because the total still looks reasonable.
 */
export function rowAreas(table, {north, pixelDeg, height}) {
  const out = new Float64Array(height);
  for (let r = 0; r < height; r++) {
    out[r] = pixelAreaM2(table, north - pixelDeg * (r + 0.5));
  }
  return out;
}

/* --------------------------------------------------------- the near regime */
/**
 * Total ground area held by each stored value in a window, in m².
 *
 * One pass. `out[v]` is the area of the pixels holding value `v`, so every question
 * the slider can ask — "built by 1994", "appeared after 2000", "undated" — is a
 * sum over a slice of this array, with nothing re-read and nothing re-decoded.
 *
 * `values` is a flat row-major array of the window's band, as `readRasters` returns
 * it. Only 8-bit class rasters belong here; see `FAR_ONLY_KINDS`.
 */
export function areaHistogram(values, {width, height, areas}) {
  if (values.length !== width * height) {
    throw new Error(`areaHistogram: ${values.length} values for a ${width}x${height} window`);
  }
  if (areas.length !== height) {
    throw new Error(`areaHistogram: ${areas.length} row areas for ${height} rows`);
  }
  const out = new Float64Array(256);
  let i = 0;
  for (let r = 0; r < height; r++) {
    const a = areas[r];
    for (let c = 0; c < width; c++, i++) out[values[i]] += a;
  }
  return out;
}

const KM2 = (m2) => m2 / 1e6;

/**
 * Turn a histogram into statistics of the SAME SHAPE the build publishes.
 *
 * That shape is the whole trick. The readout renders a `stats` object; whether it
 * came from a pixel count here or from a sum of published island figures is then
 * invisible to it, and the two regimes cannot drift into different vocabularies.
 *
 * `years` / `epochs` are the keys to emit, taken from the published statistics
 * rather than invented, so the near and far answers are comparable key by key —
 * which is what lets a test assert that they agree where they meet.
 */
export function statsFromHistogram(hist, {kind, years = [], epochs = []}) {
  if (kind === 'year') {
    const out = {extent_by_year: {}};
    let running = 0;
    let bin = 1;
    for (const y of years) {
      const target = y - YEAR_OFFSET;
      for (; bin <= target && bin < UNDATED; bin++) running += hist[bin];
      out.extent_by_year[String(y)] = round6(KM2(running));
    }
    // The undated class is built ground with no year. It belongs in the footprint
    // and in NO year bin, because a pixel with no year cannot be placed in a period
    // — which is also why the "appeared since" view refuses to draw it.
    let dated = 0;
    for (let b = 1; b < UNDATED; b++) dated += hist[b];
    out.undated_km2 = round6(KM2(hist[UNDATED]));
    out.footprint_km2 = round6(KM2(dated + hist[UNDATED]));
    return out;
  }
  if (kind === 'epoch') {
    const out = {extent_by_epoch: {}};
    let running = 0;
    let bin = 1;
    for (const e of epochs) {
      for (; bin <= e && bin < 256; bin++) running += hist[bin];
      out.extent_by_epoch[String(e)] = round6(KM2(running));
    }
    out.footprint_km2 = out.extent_by_epoch[String(epochs[epochs.length - 1])] ?? 0;
    return out;
  }
  if (kind === 'binary') {
    let total = 0;
    for (let b = 1; b < 256; b++) total += hist[b];
    return {area_km2: round6(KM2(total))};
  }
  if (kind === 'percent') {
    // The band is the percentage of the pixel that is sealed, so each pixel
    // contributes its own area scaled by its own value — never a pixel count.
    let total = 0;
    for (let b = 1; b < 256; b++) total += hist[b] * (b / 100);
    return {sealed_km2: round6(KM2(total))};
  }
  throw new Error(`statsFromHistogram: no near path for "${kind}" (see FAR_ONLY_KINDS)`);
}

const round6 = (n) => Math.round(n * 1e6) / 1e6;

/* ---------------------------------------------------------- the far regime */
/**
 * Series that are CUMULATIVE — a running total, not a per-period amount.
 *
 * The distinction decides what a missing entry means, and getting it wrong produces
 * a number that falls when it can only rise. A published per-island series ends at
 * that island's last recorded construction: Fuerteventura and La Gomera stop at
 * 2025, La Graciosa at 2023. Summing the islands at 2026 while skipping the ones
 * with no 2026 entry dropped them entirely, and the archipelago read 93.87 km² at
 * 2026 against 102.96 at 2025 — Fuerteventura's 7.622 and La Gomera's 1.522, gone.
 *
 * In a cumulative series a missing year means "nothing new was recorded", so the
 * island's last known total is carried forward. In a per-period series — the gains
 * and losses of `change_km2` — a missing period really is zero.
 */
export const CUMULATIVE_SERIES = new Set(['extent_by_year', 'extent_by_epoch', 'surface_km2']);

/**
 * Sum cumulative series across islands, carrying each one's last known value
 * forward. Before an island's first entry it contributes nothing; after its last it
 * goes on contributing that last total, because the buildings are still standing.
 */
function sumCumulative(series) {
  const keys = [...new Set(series.flatMap((o) => Object.keys(o)))]
    .sort((a, b) => Number(a) - Number(b));
  const carried = series.map(() => 0);
  const out = {};
  for (const k of keys) {
    let total = 0;
    series.forEach((o, i) => {
      const v = o[k];
      if (typeof v === 'number') carried[i] = v;
      total += carried[i];
    });
    out[k] = round6(total);
  }
  return out;
}

/** Do two bounding boxes `[w, s, e, n]` share any ground at all? */
export function intersects(a, b) {
  return a[0] < b[2] && b[0] < a[2] && a[1] < b[3] && b[1] < a[3];
}

/** The islands the view touches, in west-to-east order, as the map reads. */
export function islandsInView(view, islands) {
  return Object.entries(islands)
    .filter(([, entry]) => entry.bbox && intersects(view, entry.bbox))
    .sort((x, y) => x[1].bbox[0] - y[1].bbox[0])
    .map(([name]) => name);
}

/**
 * Sum published per-island statistics — the JavaScript twin of
 * `publish.archipelago_stats`, and deliberately the same rules.
 *
 * **Only extensive quantities are summed, and percentages are left out rather than
 * averaged.** A share of one island is not a share of two: a footprint-weighted
 * mean of eight shares lands 0.01 away from the figure `facts.py` publishes, and a
 * number that is nearly right is worse here than no number, because nothing
 * downstream can tell the difference. Labels — epoch names, period names, source
 * strings — are identical on every island and pass through unchanged.
 */
export function sumStats(entries) {
  const out = {};
  const keys = new Set();
  for (const e of entries) for (const k of Object.keys(e || {})) keys.add(k);

  for (const key of [...keys].sort()) {
    if (key.endsWith('_pct') || key.includes('share')) continue;
    const values = entries.filter((e) => e && key in e).map((e) => e[key]);
    const first = values[0];

    if (typeof first === 'number') {
      out[key] = round6(values.reduce((a, b) => a + b, 0));
    } else if (first && typeof first === 'object' && !Array.isArray(first)) {
      if (CUMULATIVE_SERIES.has(key)) { out[key] = sumCumulative(values); continue; }
      const acc = {};
      for (const v of values) {
        for (const [k2, v2] of Object.entries(v)) {
          if (typeof v2 === 'number') acc[k2] = round6((acc[k2] ?? 0) + v2);
          else if (v2 && typeof v2 === 'object' && !Array.isArray(v2)) {
            const inner = acc[k2] ?? (acc[k2] = {});
            for (const [k3, v3] of Object.entries(v2)) {
              if (typeof v3 === 'number') inner[k3] = round6((inner[k3] ?? 0) + v3);
              else if (!(k3 in inner)) inner[k3] = v3;
            }
          } else if (!(k2 in acc)) acc[k2] = v2;
        }
      }
      out[key] = acc;
    } else {
      out[key] = first;       // booleans, strings, lists: the same on every island
    }
  }
  return out;
}

/**
 * How much appeared after a given year or epoch.
 *
 * "Added since X" is the difference of two cumulative totals, and it has to be done
 * the same way wherever the series came from — a counted window or a sum of published
 * islands. It lives here rather than in the render function so `node --test` can
 * check the arithmetic, which is the same reason `stats.zonal()` is one function.
 *
 * **Undated ground is absent from these series and must stay absent.** A pixel with
 * no year cannot be placed in a period, which is also why the map refuses to draw it
 * in this mode. Clamped at zero because the series is cumulative and monotonic, so a
 * negative result can only be floating-point noise.
 */
export function addedSince(series, from) {
  const keys = Object.keys(series || {}).map(Number).sort((a, b) => a - b);
  if (!keys.length) return 0;
  const clamp = (v) => Math.min(Math.max(v, keys[0]), keys[keys.length - 1]);
  const total = series[String(keys[keys.length - 1])];
  return Math.max(0, round6(total - series[String(clamp(from))]));
}

/* ---------------------------------------------------------------- captions */
/**
 * What the number covers, in words a reader can check against the screen.
 *
 * The near regime genuinely measures the rectangle on screen, so it says so. The
 * far regime measures WHOLE islands, which is more ground than the screen shows
 * whenever an island runs off the edge — so it names them instead of claiming
 * "in view", because that claim would be false and unfalsifiable at a glance.
 */
export function describe(regime, names, total) {
  if (regime === 'near') return 'in view';
  if (names.length === 0) return 'no island in view';
  if (names.length === total) return 'all eight islands';
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  if (names.length === 3) return `${names[0]}, ${names[1]} and ${names[2]}`;
  return `${names.length} islands`;
}

/** Nothing in view is a real answer, not a missing one: the sea holds no buildings. */
export function emptyStats(kind, {years = [], epochs = []} = {}) {
  return statsFromHistogram(new Float64Array(256), {kind, years, epochs});
}
