"""Regenerate — or verify — every live figure embedded in the documents.

The documents do not contain hand-typed numbers where it matters. They contain a
call to `sensisat.facts` inside an HTML comment, and cog writes the answer next to
it. This script is the only place that knows which files carry such figures.

    python scripts/sync_docs.py            # rewrite the numbers from the build
    python scripts/sync_docs.py --check    # fail if any is stale, change nothing

Where it runs, and why each one differs:

  * `scripts/build.py` REGENERATES, because a rebuild is what makes documents
    stale. The thing that breaks them should fix them, and the change then shows up
    as a reviewable git diff rather than a silent drift.
  * `pytest` CHECKS, so the normal edit loop catches it in under a second.
  * `scripts/publish.py` CHECKS and refuses to assemble `dist/`, because a stale
    number only does harm once it is published, and that is the last moment to stop
    it.

Markers are comments in whatever syntax the file uses — HTML comments in Markdown
and the page, `//` line comments in JavaScript — so a reader sees only the number.
In code a marker can never sit INSIDE a string literal (there, "//" is text), so it
generates the entire line that carries the figure.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: Files carrying live figures. Adding one here is all it takes for its numbers to
#: be regenerated and guarded; a file not listed is simply never touched.
DOCUMENTS = [
    # published, token-level
    "viewer/about-the-data.html",
    "README.md",
    # NOT viewer/app.js: cog cannot parse JavaScript whose nested array literals end
    # in "]]]" (its own end-of-code token), and a marker can never sit inside a
    # string. The viewer instead imports viewer/facts.generated.js, written below.
    # section-level
    "docs/pipeline.md",
    "docs/validation.md",
    "docs/data-evaluation.md",
    "docs/concepts.md",
    "docs/viewer.md",
    "docs/design/scaling.md",
    "docs/design/seam-harmonization.md",
    "docs/design/figure-provenance.md",
    "CLAUDE.md",
    # NOT sensisat/layers.py: its STAC descriptions are templates filled by
    # catalog.py at write time, because a figure written into the module lags the
    # build that produced it by one run (see catalog._fill).
]

PRELUDE = ("import sensisat.facts as f; "
           "from sensisat.facts import km2, area, area_by")


FACTS_JS = ROOT / "viewer" / "facts.generated.js"


def render_facts_js() -> str:
    """The viewer's key store: every live figure the UI shows, as one ES module.

    Formatted here, in English, because these values are spliced into English
    sentences (the layer notes); the viewer's numeric readouts use the reader's
    locale separately. Strings, not numbers, so the formatting is decided once.
    """
    from sensisat import facts as f
    lo, hi, n = f.seam_drop_range()
    rows = {
        "undated_pct": f"{f.undated_share():.0f}",
        "sealed_vs_built": f"{f.sealed_vs_built_ratio():.1f}",
        "gc_growth_1995_2015_pct": f"{f.growth_pct('settlement-era-a', 'Gran Canaria', 1995, 2015):.0f}",
        "seam_main_islands": str(n),
        "seam_drop_lo_pct": f"{lo:.0f}",
        "seam_drop_hi_pct": f"{hi:.0f}",
    }
    body = "\n".join(f"  {k}: {v!r}," for k, v in rows.items()).replace("'", '"')
    return ("// GENERATED by scripts/sync_docs.py from sensisat/facts.py — do not edit.\n"
            "// One definition of each live figure the viewer shows, shared with the prose\n"
            "// page and the STAC descriptions, so a number cannot be right in one place\n"
            "// and wrong in another. Regenerate: python scripts/sync_docs.py\n"
            f"export const FACTS = {{\n{body}\n}};\n")


def sync_facts_js(check: bool) -> int:
    want = render_facts_js()
    have = FACTS_JS.read_text() if FACTS_JS.exists() else ""
    if want == have:
        return 0
    if check:
        print(f"  FAIL: {FACTS_JS.relative_to(ROOT)} is stale — run `python scripts/sync_docs.py`")
        return 5
    FACTS_JS.write_text(want)
    return 0


def run(check: bool) -> int:
    if (rc := sync_facts_js(check)):
        return rc
    present = [d for d in DOCUMENTS if (ROOT / d).exists()]
    cmd = [sys.executable, "-m", "cogapp", "-p", PRELUDE]
    cmd += ["--check", "--diff"] if check else ["-r"]
    cmd += [str(ROOT / d) for d in present]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    out = (proc.stdout + proc.stderr).strip()

    if proc.returncode == 0:
        print(f"  documents {'verified' if check else 'synced'}: {len(present)} files")
        return 0
    if check:
        print("  FAIL: a document's numbers no longer match the build.\n")
        print(out)
        print("\n  Either the document is stale — run `python scripts/sync_docs.py` —")
        print("  or the pipeline changed and the surrounding prose needs rewriting.")
        print("  This check cannot tell which; it only knows they disagree.")
    else:
        print(out)
    return proc.returncode


def figure_gate() -> int:
    """Run the whole figure gate — tests/test_documented_numbers.py — as a subprocess.

    One entry point, so `build.py` and `publish.py` cannot drift from what `pytest`
    checks: the same file, the same tests, the same exit code. Zero means every figure
    on every surface is generated, declared or excepted, no live value is typed by
    hand, and every quantity word carries its digits.
    """
    proc = subprocess.run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider",
                           str(ROOT / "tests" / "test_documented_numbers.py")],
                          cwd=ROOT, capture_output=True, text=True)
    if proc.returncode == 0:
        print("  figure gate: passed")
    else:
        tail = "\n".join(proc.stdout.strip().splitlines()[-25:])
        print("  FAIL: the figure gate — a number somewhere has no accounted source.\n")
        print(tail)
        print("\n  Full report: python -m pytest tests/test_documented_numbers.py")
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify without writing; non-zero exit if anything is stale")
    return run(ap.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
